[package]
name = "hello_world"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
axum = "0.8.1"
linkme = "0.3.32"
axum-distributed-routing = { path = "../../" }
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
